# Contribute to Our Project {.unnumbered}

We are currently working on producing the first complete edition of this resource for launch at the [LIBER Annual Conference](https://liberconference.eu/) 3-5 July 2024. Topic Guides are currently being produced through a series of in-person and online writing sprints of LIBER working group members and by direct invitation. When complete, the first edition will be deposited in the [British Library Research Repository](https://bl.iro.bl.uk/), captured in the UK Web Archive, and a DOI provided for both the overall resources and individual guides. 

The first edition Topic Guide list draws heavily on the existing skills framework and topics covered in the British Library’s Digital Scholarship Training Programme, as well as those recommended by attendees of development workshops hosted by LIBER working groups throughout 2023/2024.

## Ways to contribute to this project

- Contribute a new [**Topic Guide**](topicguides.qmd) (individually or in collaboration with others). Choose from our [**existing wishlist**](https://docs.google.com/spreadsheets/d/1FYR9UyZ7lWJOfsucZspw5sm9rmnTtHXecaYpCbVvDdI/edit#gid=851320609) or propose a new one and join a writing sprint!
- Suggest edits to an existing Topic Guide or Additional Resources by opening an [**Issue**](https://github.com/libereurope/ds-essentials/issues) or adding to existing ones on the project Github
- Join one of the [LIBER Working Groups Digital Scholarship and Digital Cultural Heritage WG](https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/) or [Data Science in Libraries](https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/) (open to all staff of [LIBER member institutions](https://libereurope.eu/liber-participants/)) to keep up with the developments of this project!

## Join a Writing Sprint! 
> <mark>Our next Topic Guide Sprint is **Tuesday May 14, 2024 9:00-11:00 (BST)** [Register Today!](https://forms.office.com/Pages/ResponsePage.aspx?id=t0ykIcP5AE-a-r0ejoi82X7ZIEJh0odPq9ej1FnpQEJUNTlTTTQ3WjBWU0gxOTdaNk1WSUpVV1FPRS4u)</mark>

If you would like to take part please [Register Today](https://forms.office.com/Pages/ResponsePage.aspx?id=t0ykIcP5AE-a-r0ejoi82X7ZIEJh0odPq9ej1FnpQEJUNTlTTTQ3WjBWU0gxOTdaNk1WSUpVV1FPRS4u) to be sent the meeting calendar invite, sprint details and access to your Topic Guide Template in case you want to prep/get started early. Feel free to contact [digitalresearch@bl.uk](mailto:digitalresearch@bl.uk) with any questions!

Preparing for the sprint:

1. Please have a quick read through the [**Welcome**](index.qmd) and [**Topic Guide**](topicguides.qmd) pages to familiarise yourself with this resource and its purpose.
2. When you [**Register**](https://forms.office.com/Pages/ResponsePage.aspx?id=t0ykIcP5AE-a-r0ejoi82X7ZIEJh0odPq9ej1FnpQEJUNTlTTTQ3WjBWU0gxOTdaNk1WSUpVV1FPRS4u) you'll see a list of our latest Topic Guide wishlist. Please check off any and all Topic Guides you would be happy to work on during the day of the sprint. Feel free to select more than one if there are a number of topics you feel happy to write about. On the day however each attendee will focus on writing just **one** Topic Guide. The information you provide before the sprint will help us organise this ahead of time so that as many Topic Guides as possible have at least one dedicated author. 
3. Please have a quick read through the **Contribution Guidance and Style Guide** section below. 
4. We'll be in touch after we receive your registration to send you more details and useful information ahead of the sprint. If you are sent a copy of the [**Topic Guide Template (Google Doc)**](https://drive.google.com/drive/folders/1okdNMn1Jg1M8Enzavuqe_elsWH0uV1p1?usp=sharing) that corresponds to your topic of choice ahead of time, add your name to the header, and feel free to add notes or even make a start on drafting your guide before the sprint day if you're keen! 

We look forward to seeing you online! 

## Contribution Guidance and Style Guide 

### Structuring the Topic Guide

Each Topic Guide follows a distince structure, beginning with a Header Section composing of a title, contributor information, published date, last modified info, and suggested citation followed by five key content blocks detailed below. Please have a look at the [IIIF Guide](iiif.qmd) as an example of how these pieces all fit together into one complete Topic Guide.

#### Header Section

- **Topic Guide Title**: IIIF
- **Contributor(s) Name and (Orcid ID)**:  Nora McGregor [(ORCID iD)](https://orcid.org/0000-0001-6560-5586)
- **Published date**: 27/03/2024
- **Suggested Citation**:  Nora McGregor, “IIIF,” *Digital Scholarship & Data Science Essentials for Library Professionals* (2024), [DOI link]

*Note: The project team will ensure each Topic Guide is given an individual DOI either through British Library Research Repository or Zenodo.* 

#### I: Introduction to the topic (*Approximately 500-700 words*)
This introduction section should be pitched at a beginner/foundational level and gives a concise overview of the topic. It should be written in a relaxed and natural way. This section does not need to contain the world’s knowledge, just enough high-level knowledge to get the key concepts across. 

>Imagine that a colleague has come to you casually asking about the topic over tea. How might you go about explaining it to them in your own words? During the course of that casual conversation what key things would you leave in and what might you leave out in the interest of getting them to a basic understanding quickly?

Linking can be used liberally for jargon busting throughout if explaining a particular term is more complex than our word count allows. Please see the Style Guidelines below for more writing tips!

#### II: Relevance to the Library Sector  (*Approximately 300-500 words*)
This section provides a clear explanation of the topics’ specific relevance to the work of libraries.

It should contain:

- A short paragraph or two setting the scene as to why the topic is relevant to the work of libraries. Here you might also like to present opportunities and, if relevant, potential challenges for libraries around the topic as well.
- 1- 3 examples of real world (or potential) applications/case studies/projects briefly explained in a 100 max word summary provided each with links to further information if available. Note that it is not necessary to write up or create a new case study yourself here! Rather, we’re looking for briefly summarised references to existing ones. If there are quite a few other examples the contributor would like to reference include, links to these can be added at the end of this section (Example: “For further case studies, visit….”).

#### III: Hands-on activity and other self-guided tutorial(s) 
The objective of this section of the topic guide is to enable learners to familiarise themselves with the basics of the topic through active practice via self-paced tutorials and hand-on activities. Authors are not expected to create new activities or tutorials in this section, but rather to provide selected links to existing hands on tutorials which are known by them to have proven value and can be personally recommended for library professionals in particular. 

The tutorials recommended should be free, online and suitable for independent study, and ideally, focussed on the library professional perspective where possible. Authors may wish to link to practical exercises or quizzes, specific online lessons that may exist in other online platforms, Juptyer Notebooks and GLAM workbench materials that provide detailed explanations of the steps learners can follow. 

For the sake of consistency across the various topic guides, it is helpful if tutorial references are structured as follows:

- The title/name of the activity/tutorial, the URL (added as a hyperlink), and citation information (please use APA Style)
- A brief, personal explanation below it (no more than 200 words) as to why the author recommends this particular tutorial, and, optionally, an indication of topics covered and the level of complexity.

#### IV: Recommended Reading & Viewing (*Approximately 200-400 words*)  
The section on recommended reading and viewing contains references to more passive learning resources such as:

- Open access articles discussing the topic at a general level, or containing contextual information.
- Video recordings of lectures about the topic, which do not demand practical activities from the viewer
Podcasts about the topic

[TODO: How should authors link to publications? Instruction here on how to use the Zotero Library?]

#### V: Taking the next steps (*Approximately 200-400 words*)  
This section provides guidance to library professionals on where to take their learning journey further. It should include:

- Where to find (local/national/international) Communities of Practice or other relevant networks and organisations who can help with furthering their understanding of the topic. 
- If relevant you might also point to specific summer school courses, conferences and events that may further enhance learning. 

### Style Guidelines

#### Writing Accessible, Natural, and Internationally Inclusive Content

To ensure consistency and inclusivity across our content, please consider these general guidelines:

- **Clarity and Simplicity**: Write in a clear and straightforward manner, using simple language that is easy to understand for learners of all backgrounds and proficiency levels.
- **Linking to Technical Terms**: When introducing technical terms or concepts that may be unfamiliar to some learners, provide hyperlinks to additional resources or definitions where they can learn more. This helps to enhance understanding and allows learners to explore topics in more depth at their own pace. Ensure that the linked resources are reliable and authoritative to provide accurate information to the learners. 
- **Avoid Colloquialisms and Regionalisms**: While it's essential to maintain a casual and natural tone, please refrain from using colloquial expressions or regionalisms that may not be universally understood by our diverse audience.
- **Cultural Sensitivity**: Be mindful of cultural differences and avoid language or examples that may be offensive or insensitive to any group of people. When providing examples or references, strive for universality and inclusivity.
- **Gender Neutrality**: Use gender-neutral language whenever possible to ensure inclusivity and avoid assumptions about gender roles or identities.
- **Global Perspective**: Consider the international nature of our audience when crafting examples, scenarios, and references. Aim for content that resonates with learners from various cultural backgrounds and geographical locations.



### *Submitting your Topic Guide*
During the workshop, you’ve been working on your Topic Guide in a Google Doc. This Google Doc can continue to serve as a ‘living document’ following the workshop until you feel the content is ready to be published to Digital Scholarship and Data Science Essentials for Library Professionals. Throughout this process, we would like to maintain an overview of the docs in terms of their status and action points using the functionality offered by GitHub Issues. 

At the end of the sprint therefore, we will ask you to head over to GitHub and open an ‘Issue’ to start a submission of your Topic Guide. We will provide an issue template which is pre-formatted as a submission checklist. Please go through the issue template and provide the necessary information relating to where the submission is currently at. Once the issue is saved, it can continue to serve as a space to continue discussion of the ongoing status of your submission and log updates where necessary, including notifying us of when it is fully ready for final review by maintainers. 

Things to note when creating an Issue for your newly created Topic Guide under development:
- If you want to include resources such as images and videos etc. which cannot be linked to via the web - you might have to provide the files themselves to us. You can attach any local files as a comment on the Issue you have created for your Topic Guide. 
- Any references used should also be added to the Zotero library and/or provided in BibTex format.
- You may request placing your Google Doc under restricted access if you wish. We will not do this by default, but we respect that some contributors would like to keep drafts private until fully ready for submission.

When your Topic Guide is ready for our review in Google Docs, please let us know by logging an update over on Github as a comment on the issue stating this. You can also tag the maintainers so they receive a notification as well. Maintainers will generally work with you on the final edits necessary for the submission through track changes and comments within the Google Doc itself. Once these have all been resolved maintainers will log a status update indicating “Review complete; Final Submission Ready; Make live” in the GitHub issue.


