# Start your own local training programme {.unnumbered}

>Contributed by: Nora McGregor, [ORCID iD](https://orcid.org/0000-0001-6560-5586) and Mia Ridge, [ORCID iD](https://orcid.org/0000-0003-3733-8120)<br>
>Original published date: 27/03/2024<br>
>Last modified: See Github page history
>
>Suggested Citation: Nora McGregor, Mia Ridge, “Start your own local training programme,” *Digital Scholarship & Data Science Essentials for Library Professionals* (2024), [DOI link tbd]

## Find your people
Get a small group of willing colleagues at your institution together and set up a way for them to communicate regularly, preferably asynchronously/remotely. We use a corporate wide MS Teams channel for this but you could also set up things like a slack channel or even a whatsapp channel. Focus on your purpose of bringing people together, think about the messaging and keep it light, "learn new stuff together" usually suffices! Try not to be too targeted, cast the net wide as people of all interests/academic disciplines/job profiles, abilities and backgrounds will undoubtedly have something to contribute: digital scholarship and data science is a collaborative affair and your group will be all the better for its diversity.

## Identify shared needs
What are problems colleagues at your institution are facing (cataloguing backlogs? etc), and what computational methods might help them to solve these? By framing digital scholarship/data science skill training as an investment that can be a helpful tool for colleagues to resolve long standing curation, creation you will find a more willing audience for your efforts. Quick wins in the digital realm (for instance in learning a tool like [Open Refine](https://openrefine.org/) to normalise and analyse catalogue records) can often build confidence very quickly and open the door to trying out new technologies. 

## Get Buy-in (if you need to!)

In some cases you may need buy-in from managers to allow staff time and space to dedicate to learning these new skills. It can be difficult to convince managers sometimes of the value of learning skills now which may take some years to truly embed or come to practical fruition. Digital Scholarship & Data Science Essentials contains loads of evidence to share with your management for why investing in digital scholarship and data science staff skills is key to sustainable digital transformation over time. Have a look at the [Skills Competency Frameworks & Key Reports](https://libereurope.github.io/ds-essentials/reports.html) sections for the latest supporting research on this. Each Topic Guide also contains useful real-life applications of new technologies being put into action under the **Relevance to the Library Sector (Case Studies/Use Cases)**. At the British Library we've started to capture individual staff digital transformation stories as well which help to demonstrate the tangible value to individuals and institutions. 

>_"The Digital Scholarship Training Programme has introduced me to new software, opened my eyes to digital opportunities, provided inspiration for me to improve, and helped me attain new skills"_ -Graham Jevon, British Library

Read more about [Graham Jevon's digital transformation journey] (https://blogs.bl.uk/digital-scholarship/2024/05/recovered-pages-graham-jevon.html) on the British Library Digital Scholarship blog or have a look at.





## Run a monthly Hack & Yack
Establishing a regular Hack & Yack meeting is a really nice way to learn something new with other colleagues. At the British Library our Hack & Yack's are once a month for two hours on a set day and time. It is a casual, hands-on session where colleagues from across all departments of the institution come together to understand a current topic or digital method and work through an online tutorial at everyone's own pace but with support of colleagues. 

We use it as an opportunity to explore new tools/techniques/applications relevant to digital research and keep our own skills up to speed. Note this is not a formal training session, we're all learning together and come to the tutorials with a variety of experience/knowledge/skills.  

Each Hack & Yack usually starts with one person, which may or may not be the organiser, giving a high-level view of the topic of the day, and then sharing one or more tutorials that the group can try out, either stepping through one online activity together as a group or providing time for everyone to explore individually at their own pace and chat about how it's going as they work through the steps. These sessions aren't recorded so that attendees can be open and frank about their experience!

Within each of these Topic Guides is a **Hands-on activity and other self-guided tutorial(s)** section that would make a perfect start for your first Hack & Yacks! 

## Start a discussion group
Whether you call it a 'reading group', a discussion group, a lunchtime series - the point is to provide regular opportunities for people to get together, and learn and support each other through discussion. You might set an article, blog post or chapter, a video or podcast.

Things we've found useful:

Begin each session with quick introductions - name and department, or name and another useful piece of information. Why? Hopefully you'll have a range of folk and they mightn't all have met before, and it means that everyone has spoken at least once right from the start.

Make it ok for people not to have finished reading, watching or listening to the thing you're discussing. You could do a show of hands to see who's finished it or not finished it. Why? There's something about 'confessing' that lets people ask questions without worrying that it was covered somewhere towards the end. It can also be useful to understand why people didn't finish (unless they just ran out of time, which is highly relatable) - did the piece get complex, jargony, boring?

Each Topic Guide has a **Recommended Reading/Viewing** section and you can also find some good starting points under [Recommended Reading Lists](https://libereurope.github.io/ds-essentials/references.html).

## Create an identity
After your group of the willing has been running for awhile it's useful to create an identify for yourselves. Perhaps you consider yourselves a network, or an interest group or maybe you'd like to start formalising your gatherings under a "training programme" moniker. Whatever you decide, it helps to bring in new folks when there is an established identity and even maybe a logo in advertisements.



