---
title: "Author Guidance & Style Guide"
format: 
   html:
     page-layout: full
sidebar: false
---
## Structuring the Topic Guide

Each Topic Guide follows a distinct structure, beginning with a Header Section composing of a title, contributor information, published date, last modified info, and suggested citation followed by five key content blocks detailed below. Please have a look at the [IIIF Guide](iiif.qmd) as an example of how these pieces all fit together into one complete DS Topic Guide.

### Front Matter

This markdown template shows an example of what information is required for the header, and how each section should be formatted. Note: The project team will ensure each Topic Guide is given an individual DOI either through Zenodo once published. 

### I: Introduction to the topic (*Approximately 500-700 words*)
This introduction section should be pitched at a beginner/foundational level and gives a concise overview of the topic. It should be written in a relaxed and natural way. This section does not need to contain the world’s knowledge, just enough high-level knowledge to get the key concepts across. 

>Imagine that a colleague has come to you casually asking about the topic over tea. How might you go about explaining it to them in your own words? During the course of that casual conversation what key things would you leave in and what might you leave out in the interest of getting them to a basic understanding quickly?

Linking can be used liberally for jargon busting throughout if explaining a particular term is more complex than our word count allows. Please see the Style Guidelines below for more writing tips!

### II: Relevance to the Library Sector  (*Approximately 300-500 words*)
This section provides a clear explanation of the topics’ specific relevance to the work of libraries.

It should contain:

- A short paragraph or two setting the scene as to why the topic is relevant to the work of libraries. Here you might also like to present opportunities and, if relevant, potential challenges for libraries around the topic as well.
- Up to 3 examples of real world (or potential) applications/case studies/projects briefly explained in a 100 max word summary provided each with links to further information if available. Note that it is not necessary to write up or create a new case study yourself here! Rather, we’re looking for briefly summarised references to existing ones. If there are quite a few other examples the contributor would like to reference include, links to these can be added at the end of this section (Example: “For further case studies, visit….”).

### III: Hands-on activity and other self-guided tutorial(s) 
The objective of this section of the topic guide is to enable learners to familiarise themselves with the basics of the topic through active practice via self-paced tutorials and hand-on activities. Authors are not expected to create new activities or tutorials in this section, but rather to provide selected links to existing hands on tutorials which are known by them to have proven value and can be personally recommended for library professionals in particular. 

The tutorials recommended should be free, online and suitable for independent study, and ideally, focussed on the library professional perspective where possible. Authors may wish to link to practical exercises or quizzes, specific online lessons that may exist in other online platforms, Juptyer Notebooks and GLAM workbench materials that provide detailed explanations of the steps learners can follow. 

For the sake of consistency across the various topic guides, it is helpful if tutorial references are structured as follows:

- The title/name of the activity/tutorial, the URL (added as a hyperlink), and citation information (please use [APA Style](https://apastyle.apa.org/instructional-aids/reference-guide.pdf) and/or provide a DOI if there is one)
- A brief, personal explanation below it (no more than 200 words) as to why the author recommends this particular tutorial, and, optionally, an indication of topics covered and the level of complexity.

### IV: Recommended Reading & Viewing (*Approximately 200-400 words*)  
The section on recommended reading and viewing contains references to more passive learning resources such as:

- Open access articles discussing the topic at a general level, or containing contextual information.
- Video recordings of lectures about the topic, which do not demand practical activities from the viewer
Podcasts about the topic

When including citations please make sure to either write them in APA Style and/or simply provide the DOI with your text so that the project team can compile a dedicated Zotero Library.

### V: Taking the next steps (*Approximately 200-400 words*)  
This section provides guidance to library professionals on where to take their learning journey further. It should include:

- Where to find (local/national/international) Communities of Practice or other relevant networks and organisations who can help with furthering their understanding of the topic. 
- If relevant you might also point to specific summer school courses, conferences and events that may further enhance learning. 

## Style Guidelines

### Writing Accessible, Natural, and Internationally Inclusive Content

To ensure consistency and inclusivity across our content, please consider these general guidelines:

- **Clarity and Simplicity**: Write in a clear and straightforward manner, using simple language that is easy to understand for learners of all backgrounds and proficiency levels.
- **Linking to Technical Terms**: When introducing technical terms or concepts that may be unfamiliar to some learners, provide hyperlinks to additional resources or definitions where they can learn more. This helps to enhance understanding and allows learners to explore topics in more depth at their own pace. Ensure that the linked resources are reliable and authoritative to provide accurate information to the learners. 
- **Avoid Colloquialisms and Regionalisms**: While it's essential to maintain a casual and natural tone, please refrain from using colloquial expressions or regionalisms that may not be universally understood by our diverse audience.
- **Cultural Sensitivity**: Be mindful of cultural differences and avoid language or examples that may be offensive or insensitive to any group of people. When providing examples or references, strive for universality and inclusivity.
- **Gender Neutrality**: Use gender-neutral language whenever possible to ensure inclusivity and avoid assumptions about gender roles or identities.
- **Global Perspective**: Consider the international nature of our audience when crafting examples, scenarios, and references. Aim for content that resonates with learners from various cultural backgrounds and geographical locations.



