# IIIF {.unnumbered}
>Contributed by: Nora McGregor, [ORCID iD](https://orcid.org/0000-0001-6560-5586)<br>
>Original published date: 27/03/2024<br>
>Last modified: See Github page history
>
>Suggested Citation: Nora McGregor, “IIIF,” *Digital Scholarship & Data Science Essentials for Library Professionals* (2024), [DOI link tbd]

## Introduction 

IIIF (pronounced “triple-eye-eff”) stands for the [International Image Interoperability Framework](https://iiif.io/). Quite a tongue twister that one, but it broadly represents two things: 

- a set of **open standards** for delivering high-quality, attributed digital objects online at scale. 
- the **open, international community** of software developers, libraries, researchers, educators, museums, universities, creative agencies, and more working together to develop and implement the IIIF APIs to make the above open standards happen. 

### Open Standard

Ever try to look at a large high-resolution digitised manuscript online only for it to take ages to load, and when it finally does you have no way to actually move around the image easily nor see any of the metadata or annotations related to it? 

Or maybe spent months on end negotiating the terms and methods around sending copies of a variety of differently sized individual images to another institution for them to host as part of collaborative project? 

> *“At its simplest, IIIF uses APIs to load images quickly and zoom smoothly without additional loading time. But IIIF also allows you to do much more, including pulling IIIF-enabled images from different sites into viewers for comparison without downloading them (at full resolution), and enabling saving links to details of images or portions of A/V files for future reference. IIIF also allows you to use many open-source tools that help you to compare, annotate, transcribe, collaborate, and more. You can even gather multiple IIIF images together from across multiple archival collections and/or institutions to create projects or exhibits without advanced technical skills”*. [-From IIIF for Archives](https://drive.google.com/file/d/1kw_M1XQ80h3QzWbIo8QYkL2Jt8YgZgEy/view)

IIIF brings a whole new efficiency to the way in which we in the cultural heritage sector go about sharing and making our digitised collections available online, while greatly expanding the functionality around the way users interact with them. It's an open standard, collaboratively developed and maintained by a host of cultural heritage institutions around the world that **defines a consistent method for the delivery of images and audio/visual files from servers to different environments on the Web** where they can then be viewed and interacted with in many ways.

Modern Web browsers understand how to display formats like .jpg and .mp4 at defined sizes, but they can't do much else with these objects. IIIF basically aligns with general Web standards that define how all browsers work and specifies a way for viewing an image or audio/visual files in a way that **enables much richer functionality** on the Web:

- Make it easier to display large images on the web in a way that is scalable (enabling deep zoom)
- Allowing easy comparison between two objects, connecting and uniting materials across institutional boundaries
- Displaying structure and metadata and annotations with the digital collection item. (For a digitised manuscript for instance this might be page order and searchable text, for audio/visual materials, that means being able to deliver complex structures (such as several reels of film that make up a single movie) along with things like captions, transcriptions/translations, annotations, and more.)

Making your collections IIIF enabled makes it easier to share your content online in a consistent way, enabling portability across different [IIIF enabled viewers](https://iiif.io/get-started/iiif-viewers/). This means essentially that rather than endless copies of your objects being shipped and sent all over the world for different projects, they can stay on your same IIIF Image server, but be accessed and displayed by viewers hosted at institutions elsewhere. 

### Open Community
IIIF is an open, global community of software developers, librarians, researchers, educators, museums, universities, creative agencies, and more that work together to develop open APIs, implement them in software, and expose images and A/V files. It’s a grassroots effort between many different institutions to solve their shared problems with delivering, managing, sharing, and working with their resources IIIF is backed by a consortium of leading cultural institutions. The IIIF community is substantial and growing, and the standard has been formally adopted by [over 100 major cultural heritage organisations worldwide](https://iiif.io/guides/finding_resources/) including a substantial number of LIBER members.

### Ok, But How Does It Work?!
If you want the deep nitty gritty technical stuff around all the APIs and how they fit together there is quite a bit of [implementation documentation](https://iiif.io/get-started/#implementers) on their website that goes into all this. But essentially, the basics behind making your own high-quality collections IIIF enabled looks a little something like this:

- Set-up a IIIF image server (developed by the community, or there are IIIF-compatible image servers available from vendors or other web hosts) and implement the IIIF Image API to make your images and audio/video materials available from there.
- Implement the IIIF Presentation API which creates the all important IIIF Manifest files (also many open source or vendor products that can help handle this bit too). IIIF Manifests combine information about your images and structural data from your metadata source. This Manifest file is really the prime unit in IIIF. It contains all the information that makes up your new IIIF enabled object, from how to display it and what information to display (such as structure or the order of pages, or even where an illustration is located within in an image if you like, it can be as complex or simple as you need!).  
- Choose one of the many [IIIF enabled viewers](https://iiif.io/get-started/iiif-viewers/) for displaying your images via your own collection site.
- Consider making your IIIF Manifests available publicly on your collection site so users can download them and work with them in all the interesting ways you've now enabled!

## Relevance to the Library Sector (Case Studies/Use Cases)
IIIF was started by a bunch of cultural heritage institutions and it shows! The intention of the consortium has always been to combine resource and effort in building viewers that reflected the way we wanted our digital collections to be displayed online, rather than everyone still spending time and resource making our own custom viewers and building our own content silos. It's brought a huge amount of efficiency too in the way that we share images with each other and researchers. It's changed the way collaborative projects are undertaken where endless metadata mapping exercises, contract negotiations around re-use and hosting, and the copying and shipping of digitised materials on external hard drives was the norm. 

There are quite a number of use cases and case studies on the [IIIF Demos page] (https://iiif.io/demos/) but let's have a look at three real life (and canonical) examples of IIIF in action.

### Deep Zoom

[TODO add case study]

### Virtual Reconstruction

The virtual reconstruction of this damaged manuscript from Châteauroux in France (Grandes Chroniques de France, ca. 1460) is probably one of the most well-known and best examples of the power of IIIF to support this use case. At some point in the manuscripts history, fourteen of its illuminations were cut out. These illuminations eventually ended up at the Bibliothèque nationale de France in the 19th century and were digitised individually. In the demo you see the reuniting of the miniatures with the full manuscript as IIIF allows a virtual repositioning of the cut out decorations with the text, virtually reconstructing the manuscript online using the Mirador Viewer so it reflects its original state. 

[TODO Embed Image]
[Mirador Viewer: Châteauroux demo](https://demos.biblissima.fr/chateauroux/demo/)

### Create a Project/Exhibition

[TODO add (exhibit.so) case study] 


## Hands-on activity and other self-guided tutorial(s)

[TODO Reformat this section, give descriptions of each recommended training]

The following are a list of our IIIF training recommendations by us to get you started!

- IIIF have created a number of excellent and free self-paced tutorials and live online workshops useful for newcomers: Overview · IIIF Online Workshop. 
- There is also the opportunity to hire a IIIF Trainer to come to deliver live bespoke training directly to your institution (for a fee): IIIF Training
- [What is IIIF? | minimal-digital (gitbook.io)](https://aeh0.gitbook.io/minimal-digital/iiif-workshop/what-is-iiif/)
- Exhibit.so


## Recommended Reading/Viewing 

[TODO Reformat this section and add links to IIIF papers]

The IIIF organisation has also created a number of useful resources alongside their training materials such as [How It Works, a plain-language guide to how the IIIF API’s work](https://iiif.io/get-started/how-iiif-works/) and a glossary of “Key concepts you’ll encounter when working with IIIF”

## Taking the next step
Learning about IIIF can be overwhelming at first, especially if you’re not a programmer, but the IIIF Community is a very supportive one and has created a number of ways to get involved and find support and help. 

I recommend checking out their community page [IIIF Community](https://iiif.io/community/) to find details of their next open community calls, or to join their Slack Channel where you can post questions and join the discussion with other users. 
