# Welcome {.unnumbered}

_Digital Scholarship & Data Science Essentials for Library Professionals_ (**DS Essentials**) is an open and collaboratively curated training reference resource. It aims to make it easier for LIBER library professionals to gain a concise overview of the new technologies that underpin digital scholarship and data science practice in research libraries today, and find trusted training materials recommendations to start their professional learning journey. <br>

The project began in late 2023 as a joint collaboration between the Digital Scholarship & Digital Cultural Heritage ([DSDCH](https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/)) and the Data Science in Libraries ([DSLib](https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/)) working groups of LIBER. Work is currently underway to create a first edition ready for the LIBER Winter Event 2024. [Contributions](contributing.qmd) to this work are very much welcome!   

## Our Aims

- <span style="color:#f0ad00;">**Present**</span> a **central destination for newcomers** to become more familiar and conversant with the foundational concepts, methods and tools of **digital scholarship and data science practice in libraries**.<br> Examplar topics include:
- <span style="color:#f0ad00;">**Help**</span> library staff gain a **better understanding** of digital scholarship and data science practice in libraries by providing **contextualised and gentle introductions to key topics** through guides, self-guided training materials, project case studies, jargon busting and recommended reading lists
- <span style="color:#f0ad00;">**Enable**</span> staff, in LIBER membership and beyond, to **explore and immediately access** a wealth of **self and group study educational resources**, available to them through a curated catalogue with faceted search and discovery
- <span style="color:#f0ad00;">**Foster**</span> a **culture of continuous learning and professional development and facilitate the development** of localised training opportunities in LIBER institutions by providing guidance and training materials suitable for self and group study
- <span style="color:#f0ad00;">**Offer**</span> a centralised, curated and trusted home **for educators to contribute**, and have reused, their high-quality training materials
- <span style="color:#f0ad00;">**Raise awareness**</span> of **local, national** and **international networks**, and associated training events, relevant to delivering state of the art services in libraries
- <span style="color:#f0ad00;">**Furnish**</span> **current reports** and **competency skills frameworks** pertaining to digital scholarship and data science in libraries


## Who is it for?
Are you someone working in or around research libraries with an interest in learning more about how to do cool and interesting things with digital collections and data at your institution? Wondering how data science techniques can help you in your work? Are you interested in gaining valuable digital literacy skills and knowledge to support emerging areas of modern scholarship such as Digital Humanities? Do you need some of the technology jargon you hear about these days demystified?

Then this resource is for you!

It is very important to us that this resource is inclusive and intellectually accessible, challenging but not terrifying and as such we focus primarily on an introductory audience where no programming or particular digital skills are required.

Though written primarily from the research library professional perspective these guides will be useful for anyone currently (or aspiring to be) working in and around digital collections and data in heritage institutions:


- Library & Information Science students
- Project managers
- Developers
- Information specialists
- Metadata Managers
- Subject librarians
- System librarians
- Institutional leadership

And so many more!


## Why this resource?

Over the past few decades, the development of excellent self-paced tutorials and training materials relating to undertaking digital scholarship and data science in libraries have proliferated online. 

For library professionals who are relatively new to this area however, it can be hard to know where to begin! Without knowing a little bit about the context of how new technologies are being deployed in research libraries, this dearth of resources can seem quite daunting. Even if you might have an idea of what learning you’d like to undertake, it can be difficult and time consuming to try and navigate the wealth of individual training resources out there on your own.

*Digital Scholarship & Data Science Essentials for Library Professionals* is a training reference resource we have developed to remove some of the barrier of having to hunt for recommended training and resources to get you on the learning ladder. 

From working with data, data management, digital storytelling, handwritten recognition technologies and more, our Topic Guides provide contextualised and gentle introductions, written from the library practitioners perspective, to a wide range of key topics and technologies relevant to working innovatively with our digital collections and data. 

## What are Topic Guides?

Topic Guides are the heart and soul of *Digital Scholarship & Data Science Essentials for Library Professionals*. The aim of each is to provide research library professionals with a gentle and concise introduction to the key topics in this area today. They offer those with no prior knowledge, quick and curated guidance to personally recommended hands-on tutorials, use-cases, articles, videos, networks and communities of practice to deepen learning.

Each Topic Guide follows a fixed structure, consisting of five components in order to make it easier to quickly find what you might need: 

- Introduction to the topic
- Relevance to the library sector (Case studies/Use cases)
- Hands-on activities and other self-guided tutorial(s)
- Recommended Reading & Viewing
- Taking the next steps (Communities of Practice)

## How to use this resource

This resource has a dual purpose; it is written as a tool for self-study but also as a guide for individuals and institutions interested in establishing their own local training programmes. 

As a self-study resource, we hope it can serve as a useful first point of entry into complex topics in digital scholarship and data science and their application in the library world. It is not meant to be completed in any particular order, rather, learners are invited to jump in and out of individual topic guides as personal curiosity or practical need dictates.

The materials here can also be utilised in group study, as part of a reading group or even a hands-on Hack & Yack. See our special section on “How to start your own training programme” for some tips and tricks from British Library Digital Research Team colleagues on utilising the materials referenced here at your own library or within your network. 
 


