# Machine Learning and AI in Libraries {.unnumbered}
>Contributed by: Nora McGregor, [ORCID iD](https://orcid.org/0000-0001-6560-5586)
>Published date: 27/03/2024
>Suggested Citation: Nora McGregor, “Machine Learning and AI in Libraries,” *Digital Scholarship & Data Science Essentials for Library Professionals* (2024), [DOI link tbd]

## Introduction


AI is mentioned absolutely everywhere these days, in movies, in the news, in our library strategies and our funding calls, but what does it really mean and is anyone even using it correctly? Let's try to get to the bottom of this!

**Artificial Intelligence (AI)** is actually a really broad field of computer science (and an umbrella term) that refers to the research and development of systems and machines capable of doing tasks that typically require human intelligence to perform, such as reasoning, problem-solving, learning, and perception. Sometimes folks may speak of and refer to AI as systems and machines that actually having true intelligence, and though todays AI systems are shockingly convincing in how well they perform, what we're seeing today are just very advanced **machine learning algorithms and models** performing specific and discrete functions extremely well! We're a long way off (if ever) from machines having sentience (or, **Generalised Artificial Intelligence (GAI)**, so don't worry! 

Whenever AI is being discussed you may often hear the term **machine learning** mentioned, and sometimes they’re used interchangeably which can be confusing. Machine learning is more specifically a core technology that is *itself* a main subfield of AI, and *also* underpins other subfields of AI like **Natural Language Processing (NLP)**, **Computer Vision (CV)**, and **Generative AI**. 

These days, AI has been further grouped into **Traditional AI** and **Generative AI**. Traditional AI refers to machine learning based systems like (NLP and CV) for doing tasks like classifying data (e.g., assigning labels to images, automatically transcribing handwritten texts, or identifying genre of digitised texts). This is the type of AI we make a whole lot of use of in the library world. **Generative AI** on the other hand refers broadly to systems whose primary function is to generate new content (e.g., conversation, books, art). This is where conversational AI systems like ChatGPT (**G**enerative **P**re-trained **T**ransformer) fall under for example and we're only just now exploring the potential applications for these new powerful Generative AI systems in library work.

**Machine learning (ML)**, again both itself a subfield of AI and a technology that underpins other fields of AI, focuses on the development of algorithms and models that allow computers to learn patterns and relationships from data and *make predictions* on new data. Instead of being explicitly programmed for specific tasks, ML algorithms use data to learn and improve their performance over time.

A **machine learning algorithm** is designed to recognize patterns, relationships, and trends in data, and they adjust their internal parameters based on examples to improve their performance over time. Machine learning algorithms play a crucial role in various applications.

A **machine learning model** represents what was learned by a machine learning algorithm. The model is created and saved after running a machine learning algorithm on training data. The model represents the rules, numbers, and any other algorithm-specific data structures required to make predictions on new data.

In the next section we'll consider one particularly common use case in order to walk us more practically through the concept of how machine learning works: automatic transcription of handwritten text. 

### But first, a quick quiz!

*Which of the following do you think would use Machine Learning?*

1. Counting the number of people in a museum using information from entry and exit barriers.
2. A search system that looks for images similar to a user submitted sketch.
3. A system that recommends library books based on what other users have ordered.
4. A queueing system that spreads people evenly between 5 ticket booths
5. A program which extracts names from documents by finding all capitalised words and checking them against a list of known names
6. A system which turns digitised handwritten documents into searchable text
7. A robot that cleans the vases in a museum without bumping into them or breaking them
 

If you answered 2, 3, 6 & 7 you are correct! The others could all be easily programmed using a simple set of easily defined rules, rather than requiring prediction.

## Relevance to the Library Sector

Cover NLP and Computer Vision here and include
Transkribus case study as an example of how models and algorithms work.

>Let's say you have 20,000 pages of handwritten manuscripts that you would like to transcribe and turn into machine readable text to allow for better search for your researchers. A task of this scale would be far too for any one, or even two, staff members to attempt. This is where machine learning comes in....

## Hands-On Activities & Self-Guided Tutorials


## Recommended Reading & Viewing



## Taking things further
