---
title: "ABOUT"
format: 
   html:
     page-layout: full
sidebar: false
---
_Digital Scholarship & Data Science Topic Guides for Library Professionals_ is a project first undertaken in 2023 as a joint collaboration between the Digital Scholarship & Digital Cultural Heritage ([DSDCH](https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/)) and the Data Science in Libraries ([DSLib](https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/)).  It is an open and collaboratively curated training reference resource that aims to:

- <span style="color:#f0ad00;">**Present**</span> a **central destination for newcomers** to become more familiar and conversant with the foundational concepts, methods and tools of **digital scholarship and data science practice in libraries**.<br>
- <span style="color:#f0ad00;">**Help**</span> library staff gain a **better understanding** of digital scholarship and data science practice in libraries by providing **contextualised and gentle introductions to key topics** through guides, self-guided training materials, project case studies, jargon busting and recommended reading lists
- <span style="color:#f0ad00;">**Enable**</span> staff, in LIBER membership and beyond, to **explore and immediately access** a wealth of **self and group study educational resources**, available to them through a curated catalogue with faceted search and discovery
- <span style="color:#f0ad00;">**Foster**</span> a **culture of continuous learning and professional development and facilitate the development** of localised training opportunities in LIBER institutions by providing guidance and training materials suitable for self and group study
- <span style="color:#f0ad00;">**Offer**</span> a centralised, curated and trusted home **for educators to contribute**, and have reused, their high-quality training materials
- <span style="color:#f0ad00;">**Raise awareness**</span> of **local, national** and **international networks**, and associated training events, relevant to delivering state of the art services in libraries
- <span style="color:#f0ad00;">**Furnish**</span> **current reports** and **competency skills frameworks** pertaining to digital scholarship and data science in libraries
 
## Are **DS Topic Guides** for me?

Are you someone working in or around research libraries with an interest in learning more about how to do cool and interesting things with digital collections and data at your institution? Wondering how data science techniques can help you in your work? Are you interested in gaining valuable digital literacy skills and knowledge to support emerging areas of modern scholarship such as Digital Humanities? Do you need some of the technology jargon you hear about these days demystified?

Then this resource is for you!

It is very important to us that the guides here are inclusive and intellectually accessible, challenging but not terrifying and as such we focus primarily on an introductory audience where no programming or particular digital skills are required.

Though written from the research library professional perspective we think these guides will be useful for anyone currently (or aspiring to be) working in and around digital collections and data in heritage institutions:

- Library & Information Science students
- Project managers
- Developers
- Information specialists
- Metadata Managers
- Subject librarians
- System librarians
- Institutional leadership

And so many more!



## Project History 

The impetus for this project has its roots in LIBER member [British Library’s Digital Scholarship Training Programme](https://web.archive.org/web/20230513003720/https://www.bl.uk/projects/digital-scholarship-training-programme/), where for over a decade now, Digital Curators there have maintained bespoke learning resources on digital scholarship tools and methods for internal use as part of their staff training courses, talks reading group and Hack & Yacks. The team there has been looking for places to share these existing resources and expertise more widely with the sector in a dedicated collaborative learning space online.

Meanwhile, both LIBER working groups noted that while the exponential expansion of digital collections, and the computational methods and tools to interact with them presented an opportunity for LIBER library professionals working within national, research, university to cultural heritage institutions, to not only support digital scholars on increasingly more complex computationally driven research, but also to apply such methods in the care and curation of heritage collections, capacity building in digital scholarship methods, including data science, was unevenly distributed across this community however.

Though training for the sector around the use of data science and computational methods in the library context has grown considerably within the last decade, fifty-eight percent of LIBER Member respondents still noted as recently as 2019 ‘technical knowledge - such as coding or tool expertise’ as the primary deficit in their environments in [Europe's Digital Humanities Landscape: A Study From LIBER's Digital Humanities & Digital Cultural Heritage Working Group](https://zenodo.org/record/3247286#.ZGXqS7XMJjS).

The provision of these valuable resources remains fragmented online and across institutions at a local, national and international level. This leads to considerable inefficiency and inconsistent skills acquisition across LIBER member institutions and sustains an imbalance between the wide-spread ambitions of scholars to undertake computational research with library and heritage collections, and a paucity of institutions with capacity to enable these. Equally, it impedes research libraries and cultural institutions from benefiting from the digital transformations computational methods can offer.

## Core Project Team  

The site and content are maintained by the Co-Chairs and select Members of the collaborating WGs listed here who act as the core project delivery team and editors of this resource.

[Jodie Double](https://libereurope.eu/member/jodie-double/), Editor [DSDCH](https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/)  
[Péter Király](https://libereurope.eu/member/peter-kiraly-phd/), Editor [DSLib](https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/)  
[Nora McGregor](https://libereurope.eu/member/nora-mcgregor/), Editor & Site Maintainer [DSDCH](https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/)  
[Peter Verhaar](https://libereurope.eu/member/peter_verhaar/), Editor [DSLib](https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/)

## Community Contributors 

Each Topic Guide is written by specific named contributors but we also welcome changes and contributions to this resource via logging issues or if you’re a more seasoned GitHub user, via pull requests to the github repository. 

## Acknowledgements

The project team would like to thank all of our LIBER working group members who have contributed to this resource and supported our endeavours here. We have taken great inspiration from other incredible training initiatives such as the [British Library Digital Scholarship Training Programme](https://web.archive.org/web/20230513003720/https://www.bl.uk/projects/digital-scholarship-training-programme/), [DH Literacy Guidebook](https://cmu-lib.github.io/dhlg/) and [The Programming Historian](https://cmu-lib.github.io/dhlg/) in the development of this resource and thank those projects for paving the way!

## Contact us

If you’d like to ask a question of the project team you can please send an email to Nora McGregor, [nora.mcgregor@bl.uk](mailto:nora.mcgregor@bl.uk) or any of Co-Chairs and select Members of the collaborating WGs listed here who act as the core project delivery team and editors of this resource.

[Jodie Double](https://libereurope.eu/member/jodie-double/), Editor [DSDCH](https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/)  
[Péter Király](https://libereurope.eu/member/peter-kiraly-phd/), Editor [DSLib](https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/)  
[Nora McGregor](https://libereurope.eu/member/nora-mcgregor/), Editor [DSDCH](https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/)  
[Peter Verhaar](https://libereurope.eu/member/peter_verhaar/), Editor [DSLib](https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/)
