---
title: "Skills Competency Frameworks & Key Reports"
format: 
   html:
     page-layout: full
sidebar: false
---

The following are Skills Competency Frameworks & Key Reports relating to supporting Digital Scholarship and Data Science for library staff

### LIBER Publications

- [LIBER Digital Skills for Library Staff & Researchers Working Group - LIBER Europe](https://libereurope.eu/working-group/liber-digital-skills-services-working-group/) have lots of resources here, including a very useful diagram [Identifying Open Science Skills for Library Staff & Researchers](https://libereurope.eu/article/open-science-skills-diagram/)

- [LIBER Job Description Repository](https://libereurope.eu/job-descriptions/#descriptions) Contains job description examples for Digital Curator and other digital roles which reference the types of skills required for such work.

- [Europe’s Digital Humanities Landscape: A Study From LIBER’s Digital Humanities & Digital Cultural Heritage Working Group](https://zenodo.org/records/3247286#.ZGXqS7XMJjS) is a report based on a Europe-wide survey run by LIBER's Digital Humanities & Digital Cultural Heritage Working Group. The survey focused on digital collections and the activities libraries undertake around them. It covered the following topics and themes including staffing/skills

### Key Publications specific to digital scholarship and data science skills for research library staff
- The British Library and the Arts and Humanities Research Council published a report on skills: [Scoping Skills and Developing Training Programme for Managing Repository Services in Cultural Heritage Organisations](https://bl.iro.bl.uk/concern/reports/c87fd1ff-5ade-4367-8dc1-f94381c4b018). There is a very useful section (Section 3.) that references several other digital skills frameworks for research library staff across Europe.


- Lippincott, Joan K. [Directions in Digital Scholarship: Support for Digital, Data-Intensive, and Computational Research in Academic Libraries](https://doi.org/10.56561/ULHJ1168). Coalition for Networked Information, June 2023. https://doi.org/10.56561/ULHJ1168

- Padilla, Thomas. [‘Responsible Operations: Data Science, Machine Learning, and AI in Libraries’](https://www.oclc.org/research/publications/2019/oclcresearch-responsible-operations-data-science-machine-learning-ai.html). OCLC, 26 August 2020.

- Cordell, R. C. (2020). [Machine Learning + Libraries: A Report on the State of the Field.](https://labs.loc.gov/static/labs/work/reports/Cordell-LOC-ML-report.pdf) LC Labs, Library of Congress. 

- Federer L. Defining data librarianship: a survey of competencies, skills, and training. J Med Libr Assoc. 2018 Jul;106(3):294-303. doi: 10.5195/jmla.2018.306. Epub 2018 Jul 1. PMID: 29962907; PMCID: PMC6013124.

### General Competencies for Librarians which include reference to digital 

- American Library Association (ALA) [Library Competencies (Various roles): Library Competencies | Tools, Publications & Resources (ala.org)](https://www.ala.org/tools/atoz/library-competencies) (USA)

- Canadian Association of Research Libraries [Competencies for Librarians in Canadian Research Libraries Publications and Documents](https://www.carl-abrc.ca/publications-and-documents/) (including specifically [Competencies-Final-EN-1-2.pdf](https://www.carl-abrc.ca/wp-content/uploads/2020/09/Competencies-Final-EN-1-2.pdf) (Canada)

- CILIP: the library and information association [Professional Knowledge & Skills Base](https://www.cilip.org.uk/page/PKSB) - (UK)







 


